### ISSUE TITLE
 getRants() throwing HttpResponseException

### ISSUE THREAD

**Issue by tahnik** [LucaScorpion/JavaRant#11]
I am not sure if this part of your plan. I thought this exception would be caught by your API? Please close the issue it that is not the case and this is the intended behavior.

Trace:
```
org.apache.http.client.HttpResponseException: Bad Request
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:69)
	at org.apache.http.client.fluent.Response.handleResponse(Response.java:90)
	at org.apache.http.client.fluent.Response.returnContent(Response.java:97)
	at com.scorpiac.javarant.DevRant.executeRequest(DevRant.java:388)
	at com.scorpiac.javarant.DevRant.get(DevRant.java:351)
	at com.scorpiac.javarant.DevRant.getRant(DevRant.java:183)
	at api.DevRantAPI.lambda$getRant$1(DevRantAPI.java:53)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by LucaScorpion** [comment]
They are caught, but right now the exceptions stack trace is still printed. Though this should indeed be changed to log something, but not the entire stack trace.

**Comment by tahnik** [comment]
Oh ok, great to hear that. Silly me.
