### ISSUE TITLE
Update for DevRant API change

### ISSUE THREAD

**Issue by DrOverbuild** [LucaScorpion/JavaRant#14]
Trying to get any rants throws a `NullPointerException` with this stack trace:

```
java.lang.NullPointerException
	at com.scorpiac.javarant.Rant.fromJson(Rant.java:26)
	at com.scorpiac.javarant.DevRant.lambda$getRants$0(DevRant.java:110)
	at com.scorpiac.javarant.DevRant.lambda$getFeed$5(DevRant.java:182)
	at com.scorpiac.javarant.Util.lambda$jsonToList$0(Util.java:25)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.scorpiac.javarant.Util.jsonToList(Util.java:25)
	at com.scorpiac.javarant.DevRant.getFeed(DevRant.java:182)
	at com.scorpiac.javarant.DevRant.getFeed(DevRant.java:172)
	at com.scorpiac.javarant.DevRant.getRants(DevRant.java:110)
```

I looked at the JSON that was returned by going to `https://www.devrant.io/api/devrant/rants?app=3&sort=recent&limit=1&skip=0` and it appears rants no longer have keys `num_upvotes` and `num_downvotes`, but instead an overall `score`.

I can probably fix this and submit a pull request myself in the next week or two but I'm just posting this in case someone believes they can fix it before I can.

**Comment by DrOverbuild** [comment]
Didn't realize there was a 2.0 branch in development that seems to be already aware of the api change
